# Generated by Django 5.0.9 on 2026-09-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_name', models.CharField(max_length=255)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('member_id', models.CharField(max_length=64)),
                ('group_number', models.CharField(blank=True, max_length=64)),
                ('effective_date', models.DateField()),
                ('copay_primary_care', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('copay_specialist', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deductible_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deductible_met', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_summary', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=64)),
                ('frequency', models.CharField(blank=True, max_length=64)),
                ('prescribing_provider', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued')], default='active', max_length=16)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
