# Generated by Django 5.0.9 on 2026-09-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_insurancesummary_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Non-binary'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], default='undisclosed', max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
