# Generated by Django 5.0.9 on 2026-09-08 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_address_line1_patient_address_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
