# Generated by Django 5.0.9 on 2026-09-09 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_healthrecord_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_given', to='patients.patient')),
            ],
        ),
    ]
